email:              labanrotich6544@gmail.com
title: Exploring Software Development
description: A journey through code ğŸ–¥ï¸, tech trends ğŸš€ and ideas ğŸ’¡
author:             Laban Kibet
baseurl:            "" 
url:                "https://laban254.github.io"

# Social Profiles
twitter_username:   labanK_
github_username:    Laban254  
linkedin_username:  laban-rotich

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-spaceship


